### ISSUE TITLE
Add new secondaty owner to mailing list

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#100] opened 2024-05-03 10:35 UTC
### Detail

With Hari leaving @manics is the only owner of the list. We should ensure a second person has access

### Actions

- [ ] Decide person to own the list
- [ ] Provide owner access

**Comment by rollercow** [comment] 2024-05-13 16:07
Is this not a duplicate of #97

**Closed** 2024-05-14 10:38 UTC
