### ISSUE TITLE
Write up documentation guidance for how to run quarterly meetings

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#81] opened 2024-03-13 16:36 UTC
### Detail

Just to make them reproducible! Include:
- How to arrange sessions (Keynote, breakouts)
- Logistics (Zoom, hackMDs etc)
- Prep at different times (1 month, 1 week, 1 day, 1 hour)

Maybe include a checklist of actions

### Actions

- [ ] Write up the above

**Comment by Davsarper** [comment] 2024-03-26 11:45
Pretty much a duplicate of #77

**Closed by Davsarper** 2024-03-26 11:45 UTC
Labels: events
